/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainShiftShiftIndexImport } from './routes/_main/_shift/shift/index'
import { Route as MainShiftShiftDetailIndexImport } from './routes/_main/_shift/shift-detail/index'

// Create Virtual Routes

const MainTransportLazyImport = createFileRoute('/_main/transport')()
const MainDashboardLazyImport = createFileRoute('/_main/dashboard')()
const AuthAuthLazyImport = createFileRoute('/_auth/auth')()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainTransportLazyRoute = MainTransportLazyImport.update({
  path: '/transport',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/transport.lazy').then((d) => d.Route),
)

const MainDashboardLazyRoute = MainDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/dashboard.lazy').then((d) => d.Route),
)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainShiftShiftIndexRoute = MainShiftShiftIndexImport.update({
  path: '/shift/',
  getParentRoute: () => MainRoute,
} as any)

const MainShiftShiftDetailIndexRoute = MainShiftShiftDetailIndexImport.update({
  path: '/shift-detail/',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/transport': {
      id: '/_main/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof MainTransportLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/_shift/shift-detail/': {
      id: '/_main/_shift/shift-detail/'
      path: '/shift-detail'
      fullPath: '/shift-detail'
      preLoaderRoute: typeof MainShiftShiftDetailIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/_shift/shift/': {
      id: '/_main/_shift/shift/'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof MainShiftShiftIndexImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainDashboardLazyRoute: typeof MainDashboardLazyRoute
  MainTransportLazyRoute: typeof MainTransportLazyRoute
  MainIndexRoute: typeof MainIndexRoute
  MainShiftShiftDetailIndexRoute: typeof MainShiftShiftDetailIndexRoute
  MainShiftShiftIndexRoute: typeof MainShiftShiftIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardLazyRoute: MainDashboardLazyRoute,
  MainTransportLazyRoute: MainTransportLazyRoute,
  MainIndexRoute: MainIndexRoute,
  MainShiftShiftDetailIndexRoute: MainShiftShiftDetailIndexRoute,
  MainShiftShiftIndexRoute: MainShiftShiftIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/transport': typeof MainTransportLazyRoute
  '/': typeof MainIndexRoute
  '/shift-detail': typeof MainShiftShiftDetailIndexRoute
  '/shift': typeof MainShiftShiftIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/transport': typeof MainTransportLazyRoute
  '/': typeof MainIndexRoute
  '/shift-detail': typeof MainShiftShiftDetailIndexRoute
  '/shift': typeof MainShiftShiftIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/dashboard': typeof MainDashboardLazyRoute
  '/_main/transport': typeof MainTransportLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/_shift/shift-detail/': typeof MainShiftShiftDetailIndexRoute
  '/_main/_shift/shift/': typeof MainShiftShiftIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/dashboard'
    | '/transport'
    | '/'
    | '/shift-detail'
    | '/shift'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/dashboard'
    | '/transport'
    | '/'
    | '/shift-detail'
    | '/shift'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/dashboard'
    | '/_main/transport'
    | '/_main/'
    | '/_main/_shift/shift-detail/'
    | '/_main/_shift/shift/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/dashboard",
        "/_main/transport",
        "/_main/",
        "/_main/_shift/shift-detail/",
        "/_main/_shift/shift/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/dashboard": {
      "filePath": "_main/dashboard.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/transport": {
      "filePath": "_main/transport.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/_shift/shift-detail/": {
      "filePath": "_main/_shift/shift-detail/index.tsx",
      "parent": "/_main"
    },
    "/_main/_shift/shift/": {
      "filePath": "_main/_shift/shift/index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
