/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainShiftShiftIndexImport } from './routes/_main/_shift/shift/index'
<<<<<<< HEAD
import { Route as MainSettingsRolesIndexImport } from './routes/_main/_settings/roles/index'
=======
import { Route as MainShiftShiftDetailIndexImport } from './routes/_main/_shift/shift-detail/index'
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9

// Create Virtual Routes

const MainTransportLazyImport = createFileRoute('/_main/transport')()
const MainDashboardLazyImport = createFileRoute('/_main/dashboard')()
const AuthAuthLazyImport = createFileRoute('/_auth/auth')()
const MainTripOrdersIndexLazyImport = createFileRoute('/_main/trip-orders/')()
const MainSettingsUsersIndexLazyImport = createFileRoute(
  '/_main/_settings/users/',
)()
const MainSettingsRolesIndexLazyImport = createFileRoute(
  '/_main/_settings/roles/',
)()
const MainSettingsPaymentTypesIndexLazyImport = createFileRoute(
  '/_main/_settings/payment-types/',
)()
const MainSettingsLocationsIndexLazyImport = createFileRoute(
  '/_main/_settings/locations/',
)()
const MainSettingsCustomersIndexLazyImport = createFileRoute(
  '/_main/_settings/customers/',
)()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainTransportLazyRoute = MainTransportLazyImport.update({
  path: '/transport',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/transport.lazy').then((d) => d.Route),
)

const MainDashboardLazyRoute = MainDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/dashboard.lazy').then((d) => d.Route),
)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainTripOrdersIndexLazyRoute = MainTripOrdersIndexLazyImport.update({
  path: '/trip-orders/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/trip-orders/index.lazy').then((d) => d.Route),
)

const MainSettingsUsersIndexLazyRoute = MainSettingsUsersIndexLazyImport.update(
  {
    path: '/users/',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/_settings/users/index.lazy').then((d) => d.Route),
)

const MainSettingsRolesIndexLazyRoute = MainSettingsRolesIndexLazyImport.update(
  {
    path: '/roles/',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/_settings/roles/index.lazy').then((d) => d.Route),
)

const MainSettingsPaymentTypesIndexLazyRoute =
  MainSettingsPaymentTypesIndexLazyImport.update({
    path: '/payment-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/payment-types/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsLocationsIndexLazyRoute =
  MainSettingsLocationsIndexLazyImport.update({
    path: '/locations/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/locations/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsCustomersIndexLazyRoute =
  MainSettingsCustomersIndexLazyImport.update({
    path: '/customers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/customers/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainShiftShiftIndexRoute = MainShiftShiftIndexImport.update({
  path: '/shift/',
  getParentRoute: () => MainRoute,
} as any)

<<<<<<< HEAD
const MainSettingsRolesIndexRoute = MainSettingsRolesIndexImport.update({
  path: '/roles/',
=======
const MainShiftShiftDetailIndexRoute = MainShiftShiftDetailIndexImport.update({
  path: '/shift-detail/',
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/transport': {
      id: '/_main/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof MainTransportLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
<<<<<<< HEAD
    '/_main/trip-orders/': {
      id: '/_main/trip-orders/'
      path: '/trip-orders'
      fullPath: '/trip-orders'
      preLoaderRoute: typeof MainTripOrdersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/roles/': {
      id: '/_main/_settings/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainSettingsRolesIndexImport
=======
    '/_main/_shift/shift-detail/': {
      id: '/_main/_shift/shift-detail/'
      path: '/shift-detail'
      fullPath: '/shift-detail'
      preLoaderRoute: typeof MainShiftShiftDetailIndexImport
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
      parentRoute: typeof MainImport
    }
    '/_main/_shift/shift/': {
      id: '/_main/_shift/shift/'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof MainShiftShiftIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/customers/': {
      id: '/_main/_settings/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MainSettingsCustomersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/locations/': {
      id: '/_main/_settings/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof MainSettingsLocationsIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/payment-types/': {
      id: '/_main/_settings/payment-types/'
      path: '/payment-types'
      fullPath: '/payment-types'
      preLoaderRoute: typeof MainSettingsPaymentTypesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/roles/': {
      id: '/_main/_settings/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainSettingsRolesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/users/': {
      id: '/_main/_settings/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainSettingsUsersIndexLazyImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainDashboardLazyRoute: typeof MainDashboardLazyRoute
  MainTransportLazyRoute: typeof MainTransportLazyRoute
  MainIndexRoute: typeof MainIndexRoute
<<<<<<< HEAD
  MainTripOrdersIndexLazyRoute: typeof MainTripOrdersIndexLazyRoute
  MainSettingsRolesIndexRoute: typeof MainSettingsRolesIndexRoute
=======
  MainShiftShiftDetailIndexRoute: typeof MainShiftShiftDetailIndexRoute
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  MainShiftShiftIndexRoute: typeof MainShiftShiftIndexRoute
  MainSettingsCustomersIndexLazyRoute: typeof MainSettingsCustomersIndexLazyRoute
  MainSettingsLocationsIndexLazyRoute: typeof MainSettingsLocationsIndexLazyRoute
  MainSettingsPaymentTypesIndexLazyRoute: typeof MainSettingsPaymentTypesIndexLazyRoute
  MainSettingsRolesIndexLazyRoute: typeof MainSettingsRolesIndexLazyRoute
  MainSettingsUsersIndexLazyRoute: typeof MainSettingsUsersIndexLazyRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardLazyRoute: MainDashboardLazyRoute,
  MainTransportLazyRoute: MainTransportLazyRoute,
  MainIndexRoute: MainIndexRoute,
<<<<<<< HEAD
  MainTripOrdersIndexLazyRoute: MainTripOrdersIndexLazyRoute,
  MainSettingsRolesIndexRoute: MainSettingsRolesIndexRoute,
=======
  MainShiftShiftDetailIndexRoute: MainShiftShiftDetailIndexRoute,
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  MainShiftShiftIndexRoute: MainShiftShiftIndexRoute,
  MainSettingsCustomersIndexLazyRoute: MainSettingsCustomersIndexLazyRoute,
  MainSettingsLocationsIndexLazyRoute: MainSettingsLocationsIndexLazyRoute,
  MainSettingsPaymentTypesIndexLazyRoute:
    MainSettingsPaymentTypesIndexLazyRoute,
  MainSettingsRolesIndexLazyRoute: MainSettingsRolesIndexLazyRoute,
  MainSettingsUsersIndexLazyRoute: MainSettingsUsersIndexLazyRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/transport': typeof MainTransportLazyRoute
  '/': typeof MainIndexRoute
<<<<<<< HEAD
  '/trip-orders': typeof MainTripOrdersIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexRoute
=======
  '/shift-detail': typeof MainShiftShiftDetailIndexRoute
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  '/shift': typeof MainShiftShiftIndexRoute
  '/customers': typeof MainSettingsCustomersIndexLazyRoute
  '/locations': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexLazyRoute
  '/users': typeof MainSettingsUsersIndexLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/transport': typeof MainTransportLazyRoute
  '/': typeof MainIndexRoute
<<<<<<< HEAD
  '/trip-orders': typeof MainTripOrdersIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexRoute
=======
  '/shift-detail': typeof MainShiftShiftDetailIndexRoute
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  '/shift': typeof MainShiftShiftIndexRoute
  '/customers': typeof MainSettingsCustomersIndexLazyRoute
  '/locations': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexLazyRoute
  '/users': typeof MainSettingsUsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/dashboard': typeof MainDashboardLazyRoute
  '/_main/transport': typeof MainTransportLazyRoute
  '/_main/': typeof MainIndexRoute
<<<<<<< HEAD
  '/_main/trip-orders/': typeof MainTripOrdersIndexLazyRoute
  '/_main/_settings/roles/': typeof MainSettingsRolesIndexRoute
=======
  '/_main/_shift/shift-detail/': typeof MainShiftShiftDetailIndexRoute
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
  '/_main/_shift/shift/': typeof MainShiftShiftIndexRoute
  '/_main/_settings/customers/': typeof MainSettingsCustomersIndexLazyRoute
  '/_main/_settings/locations/': typeof MainSettingsLocationsIndexLazyRoute
  '/_main/_settings/payment-types/': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/_main/_settings/roles/': typeof MainSettingsRolesIndexLazyRoute
  '/_main/_settings/users/': typeof MainSettingsUsersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/dashboard'
    | '/transport'
    | '/'
<<<<<<< HEAD
    | '/trip-orders'
    | '/roles'
=======
    | '/shift-detail'
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
    | '/shift'
    | '/customers'
    | '/locations'
    | '/payment-types'
    | '/roles'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/dashboard'
    | '/transport'
    | '/'
<<<<<<< HEAD
    | '/trip-orders'
    | '/roles'
=======
    | '/shift-detail'
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
    | '/shift'
    | '/customers'
    | '/locations'
    | '/payment-types'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/dashboard'
    | '/_main/transport'
    | '/_main/'
<<<<<<< HEAD
    | '/_main/trip-orders/'
    | '/_main/_settings/roles/'
=======
    | '/_main/_shift/shift-detail/'
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
    | '/_main/_shift/shift/'
    | '/_main/_settings/customers/'
    | '/_main/_settings/locations/'
    | '/_main/_settings/payment-types/'
    | '/_main/_settings/roles/'
    | '/_main/_settings/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/dashboard",
        "/_main/transport",
        "/_main/",
<<<<<<< HEAD
        "/_main/trip-orders/",
        "/_main/_settings/roles/",
=======
        "/_main/_shift/shift-detail/",
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
        "/_main/_shift/shift/",
        "/_main/_settings/customers/",
        "/_main/_settings/locations/",
        "/_main/_settings/payment-types/",
        "/_main/_settings/roles/",
        "/_main/_settings/users/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/dashboard": {
      "filePath": "_main/dashboard.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/transport": {
      "filePath": "_main/transport.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
<<<<<<< HEAD
    "/_main/trip-orders/": {
      "filePath": "_main/trip-orders/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/roles/": {
      "filePath": "_main/_settings/roles/index.tsx",
=======
    "/_main/_shift/shift-detail/": {
      "filePath": "_main/_shift/shift-detail/index.tsx",
>>>>>>> 0b07a93fdaccfe36e1d38ef91792c6957d157ba9
      "parent": "/_main"
    },
    "/_main/_shift/shift/": {
      "filePath": "_main/_shift/shift/index.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/customers/": {
      "filePath": "_main/_settings/customers/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/locations/": {
      "filePath": "_main/_settings/locations/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/payment-types/": {
      "filePath": "_main/_settings/payment-types/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/roles/": {
      "filePath": "_main/_settings/roles/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/users/": {
      "filePath": "_main/_settings/users/index.lazy.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
