/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainTrucksTruckDetailIdImport } from './routes/_main/_trucks/truck-detail/$id'
import { Route as MainTrucksOrdersIdImport } from './routes/_main/_trucks/orders/$id'
import { Route as MainManagersManagerTripsIdImport } from './routes/_main/_managers/manager-trips/$id'
import { Route as MainTripTripParentIdIndexImport } from './routes/_main/_trip/trip/$parentId/index'
import { Route as MainTripTripParentIdChildIdImport } from './routes/_main/_trip/trip/$parentId/$childId'
import { Route as MainManagersManagerTripsManagerReysIdImport } from './routes/_main/_managers/manager-trips/manager-reys/$id'

// Create Virtual Routes

const MainDashboardLazyImport = createFileRoute('/_main/dashboard')()
const AuthAuthLazyImport = createFileRoute('/_auth/auth')()
const MainTexnikCheckIndexLazyImport = createFileRoute('/_main/texnik-check/')()
const MainKassaIndexLazyImport = createFileRoute('/_main/kassa/')()
const MainManagersManagersLazyImport = createFileRoute(
  '/_main/_managers/managers',
)()
const MainTrucksTruckIndexLazyImport = createFileRoute(
  '/_main/_trucks/truck/',
)()
const MainTripTripIndexLazyImport = createFileRoute('/_main/_trip/trip/')()
const MainSettingsVehicleTypesIndexLazyImport = createFileRoute(
  '/_main/_settings/vehicle-types/',
)()
const MainSettingsUsersIndexLazyImport = createFileRoute(
  '/_main/_settings/users/',
)()
const MainSettingsRolesIndexLazyImport = createFileRoute(
  '/_main/_settings/roles/',
)()
const MainSettingsPaymentTypesIndexLazyImport = createFileRoute(
  '/_main/_settings/payment-types/',
)()
const MainSettingsLocationsIndexLazyImport = createFileRoute(
  '/_main/_settings/locations/',
)()
const MainSettingsExpenseTypesIndexLazyImport = createFileRoute(
  '/_main/_settings/expense-types/',
)()
const MainSettingsDriversIndexLazyImport = createFileRoute(
  '/_main/_settings/drivers/',
)()
const MainSettingsCustomersIndexLazyImport = createFileRoute(
  '/_main/_settings/customers/',
)()
const MainSettingsCargoTypesIndexLazyImport = createFileRoute(
  '/_main/_settings/cargo-types/',
)()
const MainManagersTransportsIndexLazyImport = createFileRoute(
  '/_main/_managers/transports/',
)()
const MainManagersTechnicCheckIndexLazyImport = createFileRoute(
  '/_main/_managers/technic-check/',
)()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainDashboardLazyRoute = MainDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/dashboard.lazy').then((d) => d.Route),
)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainTexnikCheckIndexLazyRoute = MainTexnikCheckIndexLazyImport.update({
  path: '/texnik-check/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/texnik-check/index.lazy').then((d) => d.Route),
)

const MainKassaIndexLazyRoute = MainKassaIndexLazyImport.update({
  path: '/kassa/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/kassa/index.lazy').then((d) => d.Route),
)

const MainManagersManagersLazyRoute = MainManagersManagersLazyImport.update({
  path: '/managers',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/_managers/managers.lazy').then((d) => d.Route),
)

const MainTrucksTruckIndexLazyRoute = MainTrucksTruckIndexLazyImport.update({
  path: '/truck/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/_trucks/truck/index.lazy').then((d) => d.Route),
)

const MainTripTripIndexLazyRoute = MainTripTripIndexLazyImport.update({
  path: '/trip/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/_trip/trip/index.lazy').then((d) => d.Route),
)

const MainSettingsVehicleTypesIndexLazyRoute =
  MainSettingsVehicleTypesIndexLazyImport.update({
    path: '/vehicle-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/vehicle-types/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsUsersIndexLazyRoute = MainSettingsUsersIndexLazyImport.update(
  {
    path: '/users/',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/_settings/users/index.lazy').then((d) => d.Route),
)

const MainSettingsRolesIndexLazyRoute = MainSettingsRolesIndexLazyImport.update(
  {
    path: '/roles/',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/_settings/roles/index.lazy').then((d) => d.Route),
)

const MainSettingsPaymentTypesIndexLazyRoute =
  MainSettingsPaymentTypesIndexLazyImport.update({
    path: '/payment-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/payment-types/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsLocationsIndexLazyRoute =
  MainSettingsLocationsIndexLazyImport.update({
    path: '/locations/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/locations/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsExpenseTypesIndexLazyRoute =
  MainSettingsExpenseTypesIndexLazyImport.update({
    path: '/expense-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/expense-types/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsDriversIndexLazyRoute =
  MainSettingsDriversIndexLazyImport.update({
    path: '/drivers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/drivers/index.lazy').then((d) => d.Route),
  )

const MainSettingsCustomersIndexLazyRoute =
  MainSettingsCustomersIndexLazyImport.update({
    path: '/customers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/customers/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsCargoTypesIndexLazyRoute =
  MainSettingsCargoTypesIndexLazyImport.update({
    path: '/cargo-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/cargo-types/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainManagersTransportsIndexLazyRoute =
  MainManagersTransportsIndexLazyImport.update({
    path: '/transports/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_managers/transports/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainManagersTechnicCheckIndexLazyRoute =
  MainManagersTechnicCheckIndexLazyImport.update({
    path: '/technic-check/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_managers/technic-check/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainTrucksTruckDetailIdRoute = MainTrucksTruckDetailIdImport.update({
  path: '/truck-detail/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainTrucksOrdersIdRoute = MainTrucksOrdersIdImport.update({
  path: '/orders/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainManagersManagerTripsIdRoute = MainManagersManagerTripsIdImport.update(
  {
    path: '/manager-trips/$id',
    getParentRoute: () => MainRoute,
  } as any,
)

const MainTripTripParentIdIndexRoute = MainTripTripParentIdIndexImport.update({
  path: '/trip/$parentId/',
  getParentRoute: () => MainRoute,
} as any)

const MainTripTripParentIdChildIdRoute =
  MainTripTripParentIdChildIdImport.update({
    path: '/trip/$parentId/$childId',
    getParentRoute: () => MainRoute,
  } as any)

const MainManagersManagerTripsManagerReysIdRoute =
  MainManagersManagerTripsManagerReysIdImport.update({
    path: '/manager-trips/manager-reys/$id',
    getParentRoute: () => MainRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/_managers/managers': {
      id: '/_main/_managers/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof MainManagersManagersLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/kassa/': {
      id: '/_main/kassa/'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof MainKassaIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/texnik-check/': {
      id: '/_main/texnik-check/'
      path: '/texnik-check'
      fullPath: '/texnik-check'
      preLoaderRoute: typeof MainTexnikCheckIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_managers/manager-trips/$id': {
      id: '/_main/_managers/manager-trips/$id'
      path: '/manager-trips/$id'
      fullPath: '/manager-trips/$id'
      preLoaderRoute: typeof MainManagersManagerTripsIdImport
      parentRoute: typeof MainImport
    }
    '/_main/_trucks/orders/$id': {
      id: '/_main/_trucks/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof MainTrucksOrdersIdImport
      parentRoute: typeof MainImport
    }
    '/_main/_trucks/truck-detail/$id': {
      id: '/_main/_trucks/truck-detail/$id'
      path: '/truck-detail/$id'
      fullPath: '/truck-detail/$id'
      preLoaderRoute: typeof MainTrucksTruckDetailIdImport
      parentRoute: typeof MainImport
    }
    '/_main/_managers/technic-check/': {
      id: '/_main/_managers/technic-check/'
      path: '/technic-check'
      fullPath: '/technic-check'
      preLoaderRoute: typeof MainManagersTechnicCheckIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_managers/transports/': {
      id: '/_main/_managers/transports/'
      path: '/transports'
      fullPath: '/transports'
      preLoaderRoute: typeof MainManagersTransportsIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/cargo-types/': {
      id: '/_main/_settings/cargo-types/'
      path: '/cargo-types'
      fullPath: '/cargo-types'
      preLoaderRoute: typeof MainSettingsCargoTypesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/customers/': {
      id: '/_main/_settings/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MainSettingsCustomersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/drivers/': {
      id: '/_main/_settings/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof MainSettingsDriversIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/expense-types/': {
      id: '/_main/_settings/expense-types/'
      path: '/expense-types'
      fullPath: '/expense-types'
      preLoaderRoute: typeof MainSettingsExpenseTypesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/locations/': {
      id: '/_main/_settings/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof MainSettingsLocationsIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/payment-types/': {
      id: '/_main/_settings/payment-types/'
      path: '/payment-types'
      fullPath: '/payment-types'
      preLoaderRoute: typeof MainSettingsPaymentTypesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/roles/': {
      id: '/_main/_settings/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainSettingsRolesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/users/': {
      id: '/_main/_settings/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainSettingsUsersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_settings/vehicle-types/': {
      id: '/_main/_settings/vehicle-types/'
      path: '/vehicle-types'
      fullPath: '/vehicle-types'
      preLoaderRoute: typeof MainSettingsVehicleTypesIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_trip/trip/': {
      id: '/_main/_trip/trip/'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof MainTripTripIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_trucks/truck/': {
      id: '/_main/_trucks/truck/'
      path: '/truck'
      fullPath: '/truck'
      preLoaderRoute: typeof MainTrucksTruckIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/_managers/manager-trips/manager-reys/$id': {
      id: '/_main/_managers/manager-trips/manager-reys/$id'
      path: '/manager-trips/manager-reys/$id'
      fullPath: '/manager-trips/manager-reys/$id'
      preLoaderRoute: typeof MainManagersManagerTripsManagerReysIdImport
      parentRoute: typeof MainImport
    }
    '/_main/_trip/trip/$parentId/$childId': {
      id: '/_main/_trip/trip/$parentId/$childId'
      path: '/trip/$parentId/$childId'
      fullPath: '/trip/$parentId/$childId'
      preLoaderRoute: typeof MainTripTripParentIdChildIdImport
      parentRoute: typeof MainImport
    }
    '/_main/_trip/trip/$parentId/': {
      id: '/_main/_trip/trip/$parentId/'
      path: '/trip/$parentId'
      fullPath: '/trip/$parentId'
      preLoaderRoute: typeof MainTripTripParentIdIndexImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainDashboardLazyRoute: typeof MainDashboardLazyRoute
  MainIndexRoute: typeof MainIndexRoute
  MainManagersManagersLazyRoute: typeof MainManagersManagersLazyRoute
  MainKassaIndexLazyRoute: typeof MainKassaIndexLazyRoute
  MainTexnikCheckIndexLazyRoute: typeof MainTexnikCheckIndexLazyRoute
  MainManagersManagerTripsIdRoute: typeof MainManagersManagerTripsIdRoute
  MainTrucksOrdersIdRoute: typeof MainTrucksOrdersIdRoute
  MainTrucksTruckDetailIdRoute: typeof MainTrucksTruckDetailIdRoute
  MainManagersTechnicCheckIndexLazyRoute: typeof MainManagersTechnicCheckIndexLazyRoute
  MainManagersTransportsIndexLazyRoute: typeof MainManagersTransportsIndexLazyRoute
  MainSettingsCargoTypesIndexLazyRoute: typeof MainSettingsCargoTypesIndexLazyRoute
  MainSettingsCustomersIndexLazyRoute: typeof MainSettingsCustomersIndexLazyRoute
  MainSettingsDriversIndexLazyRoute: typeof MainSettingsDriversIndexLazyRoute
  MainSettingsExpenseTypesIndexLazyRoute: typeof MainSettingsExpenseTypesIndexLazyRoute
  MainSettingsLocationsIndexLazyRoute: typeof MainSettingsLocationsIndexLazyRoute
  MainSettingsPaymentTypesIndexLazyRoute: typeof MainSettingsPaymentTypesIndexLazyRoute
  MainSettingsRolesIndexLazyRoute: typeof MainSettingsRolesIndexLazyRoute
  MainSettingsUsersIndexLazyRoute: typeof MainSettingsUsersIndexLazyRoute
  MainSettingsVehicleTypesIndexLazyRoute: typeof MainSettingsVehicleTypesIndexLazyRoute
  MainTripTripIndexLazyRoute: typeof MainTripTripIndexLazyRoute
  MainTrucksTruckIndexLazyRoute: typeof MainTrucksTruckIndexLazyRoute
  MainManagersManagerTripsManagerReysIdRoute: typeof MainManagersManagerTripsManagerReysIdRoute
  MainTripTripParentIdChildIdRoute: typeof MainTripTripParentIdChildIdRoute
  MainTripTripParentIdIndexRoute: typeof MainTripTripParentIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardLazyRoute: MainDashboardLazyRoute,
  MainIndexRoute: MainIndexRoute,
  MainManagersManagersLazyRoute: MainManagersManagersLazyRoute,
  MainKassaIndexLazyRoute: MainKassaIndexLazyRoute,
  MainTexnikCheckIndexLazyRoute: MainTexnikCheckIndexLazyRoute,
  MainManagersManagerTripsIdRoute: MainManagersManagerTripsIdRoute,
  MainTrucksOrdersIdRoute: MainTrucksOrdersIdRoute,
  MainTrucksTruckDetailIdRoute: MainTrucksTruckDetailIdRoute,
  MainManagersTechnicCheckIndexLazyRoute:
    MainManagersTechnicCheckIndexLazyRoute,
  MainManagersTransportsIndexLazyRoute: MainManagersTransportsIndexLazyRoute,
  MainSettingsCargoTypesIndexLazyRoute: MainSettingsCargoTypesIndexLazyRoute,
  MainSettingsCustomersIndexLazyRoute: MainSettingsCustomersIndexLazyRoute,
  MainSettingsDriversIndexLazyRoute: MainSettingsDriversIndexLazyRoute,
  MainSettingsExpenseTypesIndexLazyRoute:
    MainSettingsExpenseTypesIndexLazyRoute,
  MainSettingsLocationsIndexLazyRoute: MainSettingsLocationsIndexLazyRoute,
  MainSettingsPaymentTypesIndexLazyRoute:
    MainSettingsPaymentTypesIndexLazyRoute,
  MainSettingsRolesIndexLazyRoute: MainSettingsRolesIndexLazyRoute,
  MainSettingsUsersIndexLazyRoute: MainSettingsUsersIndexLazyRoute,
  MainSettingsVehicleTypesIndexLazyRoute:
    MainSettingsVehicleTypesIndexLazyRoute,
  MainTripTripIndexLazyRoute: MainTripTripIndexLazyRoute,
  MainTrucksTruckIndexLazyRoute: MainTrucksTruckIndexLazyRoute,
  MainManagersManagerTripsManagerReysIdRoute:
    MainManagersManagerTripsManagerReysIdRoute,
  MainTripTripParentIdChildIdRoute: MainTripTripParentIdChildIdRoute,
  MainTripTripParentIdIndexRoute: MainTripTripParentIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/': typeof MainIndexRoute
  '/managers': typeof MainManagersManagersLazyRoute
  '/kassa': typeof MainKassaIndexLazyRoute
  '/texnik-check': typeof MainTexnikCheckIndexLazyRoute
  '/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/orders/$id': typeof MainTrucksOrdersIdRoute
  '/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/technic-check': typeof MainManagersTechnicCheckIndexLazyRoute
  '/transports': typeof MainManagersTransportsIndexLazyRoute
  '/cargo-types': typeof MainSettingsCargoTypesIndexLazyRoute
  '/customers': typeof MainSettingsCustomersIndexLazyRoute
  '/drivers': typeof MainSettingsDriversIndexLazyRoute
  '/expense-types': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/locations': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexLazyRoute
  '/users': typeof MainSettingsUsersIndexLazyRoute
  '/vehicle-types': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/trip': typeof MainTripTripIndexLazyRoute
  '/truck': typeof MainTrucksTruckIndexLazyRoute
  '/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/trip/$parentId': typeof MainTripTripParentIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/': typeof MainIndexRoute
  '/managers': typeof MainManagersManagersLazyRoute
  '/kassa': typeof MainKassaIndexLazyRoute
  '/texnik-check': typeof MainTexnikCheckIndexLazyRoute
  '/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/orders/$id': typeof MainTrucksOrdersIdRoute
  '/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/technic-check': typeof MainManagersTechnicCheckIndexLazyRoute
  '/transports': typeof MainManagersTransportsIndexLazyRoute
  '/cargo-types': typeof MainSettingsCargoTypesIndexLazyRoute
  '/customers': typeof MainSettingsCustomersIndexLazyRoute
  '/drivers': typeof MainSettingsDriversIndexLazyRoute
  '/expense-types': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/locations': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexLazyRoute
  '/users': typeof MainSettingsUsersIndexLazyRoute
  '/vehicle-types': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/trip': typeof MainTripTripIndexLazyRoute
  '/truck': typeof MainTrucksTruckIndexLazyRoute
  '/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/trip/$parentId': typeof MainTripTripParentIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/dashboard': typeof MainDashboardLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/_managers/managers': typeof MainManagersManagersLazyRoute
  '/_main/kassa/': typeof MainKassaIndexLazyRoute
  '/_main/texnik-check/': typeof MainTexnikCheckIndexLazyRoute
  '/_main/_managers/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/_main/_trucks/orders/$id': typeof MainTrucksOrdersIdRoute
  '/_main/_trucks/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/_main/_managers/technic-check/': typeof MainManagersTechnicCheckIndexLazyRoute
  '/_main/_managers/transports/': typeof MainManagersTransportsIndexLazyRoute
  '/_main/_settings/cargo-types/': typeof MainSettingsCargoTypesIndexLazyRoute
  '/_main/_settings/customers/': typeof MainSettingsCustomersIndexLazyRoute
  '/_main/_settings/drivers/': typeof MainSettingsDriversIndexLazyRoute
  '/_main/_settings/expense-types/': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/_main/_settings/locations/': typeof MainSettingsLocationsIndexLazyRoute
  '/_main/_settings/payment-types/': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/_main/_settings/roles/': typeof MainSettingsRolesIndexLazyRoute
  '/_main/_settings/users/': typeof MainSettingsUsersIndexLazyRoute
  '/_main/_settings/vehicle-types/': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/_main/_trip/trip/': typeof MainTripTripIndexLazyRoute
  '/_main/_trucks/truck/': typeof MainTrucksTruckIndexLazyRoute
  '/_main/_managers/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/_main/_trip/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/_main/_trip/trip/$parentId/': typeof MainTripTripParentIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/dashboard'
    | '/'
    | '/managers'
    | '/kassa'
    | '/texnik-check'
    | '/manager-trips/$id'
    | '/orders/$id'
    | '/truck-detail/$id'
    | '/technic-check'
    | '/transports'
    | '/cargo-types'
    | '/customers'
    | '/drivers'
    | '/expense-types'
    | '/locations'
    | '/payment-types'
    | '/roles'
    | '/users'
    | '/vehicle-types'
    | '/trip'
    | '/truck'
    | '/manager-trips/manager-reys/$id'
    | '/trip/$parentId/$childId'
    | '/trip/$parentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/dashboard'
    | '/'
    | '/managers'
    | '/kassa'
    | '/texnik-check'
    | '/manager-trips/$id'
    | '/orders/$id'
    | '/truck-detail/$id'
    | '/technic-check'
    | '/transports'
    | '/cargo-types'
    | '/customers'
    | '/drivers'
    | '/expense-types'
    | '/locations'
    | '/payment-types'
    | '/roles'
    | '/users'
    | '/vehicle-types'
    | '/trip'
    | '/truck'
    | '/manager-trips/manager-reys/$id'
    | '/trip/$parentId/$childId'
    | '/trip/$parentId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/dashboard'
    | '/_main/'
    | '/_main/_managers/managers'
    | '/_main/kassa/'
    | '/_main/texnik-check/'
    | '/_main/_managers/manager-trips/$id'
    | '/_main/_trucks/orders/$id'
    | '/_main/_trucks/truck-detail/$id'
    | '/_main/_managers/technic-check/'
    | '/_main/_managers/transports/'
    | '/_main/_settings/cargo-types/'
    | '/_main/_settings/customers/'
    | '/_main/_settings/drivers/'
    | '/_main/_settings/expense-types/'
    | '/_main/_settings/locations/'
    | '/_main/_settings/payment-types/'
    | '/_main/_settings/roles/'
    | '/_main/_settings/users/'
    | '/_main/_settings/vehicle-types/'
    | '/_main/_trip/trip/'
    | '/_main/_trucks/truck/'
    | '/_main/_managers/manager-trips/manager-reys/$id'
    | '/_main/_trip/trip/$parentId/$childId'
    | '/_main/_trip/trip/$parentId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/dashboard",
        "/_main/",
        "/_main/_managers/managers",
        "/_main/kassa/",
        "/_main/texnik-check/",
        "/_main/_managers/manager-trips/$id",
        "/_main/_trucks/orders/$id",
        "/_main/_trucks/truck-detail/$id",
        "/_main/_managers/technic-check/",
        "/_main/_managers/transports/",
        "/_main/_settings/cargo-types/",
        "/_main/_settings/customers/",
        "/_main/_settings/drivers/",
        "/_main/_settings/expense-types/",
        "/_main/_settings/locations/",
        "/_main/_settings/payment-types/",
        "/_main/_settings/roles/",
        "/_main/_settings/users/",
        "/_main/_settings/vehicle-types/",
        "/_main/_trip/trip/",
        "/_main/_trucks/truck/",
        "/_main/_managers/manager-trips/manager-reys/$id",
        "/_main/_trip/trip/$parentId/$childId",
        "/_main/_trip/trip/$parentId/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/dashboard": {
      "filePath": "_main/dashboard.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/_managers/managers": {
      "filePath": "_main/_managers/managers.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/kassa/": {
      "filePath": "_main/kassa/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/texnik-check/": {
      "filePath": "_main/texnik-check/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_managers/manager-trips/$id": {
      "filePath": "_main/_managers/manager-trips/$id.tsx",
      "parent": "/_main"
    },
    "/_main/_trucks/orders/$id": {
      "filePath": "_main/_trucks/orders/$id.tsx",
      "parent": "/_main"
    },
    "/_main/_trucks/truck-detail/$id": {
      "filePath": "_main/_trucks/truck-detail/$id.tsx",
      "parent": "/_main"
    },
    "/_main/_managers/technic-check/": {
      "filePath": "_main/_managers/technic-check/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_managers/transports/": {
      "filePath": "_main/_managers/transports/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/cargo-types/": {
      "filePath": "_main/_settings/cargo-types/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/customers/": {
      "filePath": "_main/_settings/customers/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/drivers/": {
      "filePath": "_main/_settings/drivers/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/expense-types/": {
      "filePath": "_main/_settings/expense-types/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/locations/": {
      "filePath": "_main/_settings/locations/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/payment-types/": {
      "filePath": "_main/_settings/payment-types/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/roles/": {
      "filePath": "_main/_settings/roles/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/users/": {
      "filePath": "_main/_settings/users/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_settings/vehicle-types/": {
      "filePath": "_main/_settings/vehicle-types/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_trip/trip/": {
      "filePath": "_main/_trip/trip/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_trucks/truck/": {
      "filePath": "_main/_trucks/truck/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/_managers/manager-trips/manager-reys/$id": {
      "filePath": "_main/_managers/manager-trips/manager-reys/$id.tsx",
      "parent": "/_main"
    },
    "/_main/_trip/trip/$parentId/$childId": {
      "filePath": "_main/_trip/trip/$parentId/$childId.tsx",
      "parent": "/_main"
    },
    "/_main/_trip/trip/$parentId/": {
      "filePath": "_main/_trip/trip/$parentId/index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
