/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTrucksTruckDetailIdRouteImport } from './routes/_main/_trucks/truck-detail/$id'
import { Route as MainTrucksOrdersIdRouteImport } from './routes/_main/_trucks/orders/$id'
import { Route as MainManagersManagerTripsIdRouteImport } from './routes/_main/_managers/manager-trips/$id'
import { Route as MainTripTripParentIdIndexRouteImport } from './routes/_main/_trip/trip/$parentId/index'
import { Route as MainTripTripParentIdChildIdRouteImport } from './routes/_main/_trip/trip/$parentId/$childId'
import { Route as MainManagersManagerTripsManagerReysIdRouteImport } from './routes/_main/_managers/manager-trips/manager-reys/$id'

const MainDashboardLazyRouteImport = createFileRoute('/_main/dashboard')()
const AuthAuthLazyRouteImport = createFileRoute('/_auth/auth')()
const MainTexnikCheckIndexLazyRouteImport = createFileRoute(
  '/_main/texnik-check/',
)()
const MainMoliyaIndexLazyRouteImport = createFileRoute('/_main/moliya/')()
const MainKassaIndexLazyRouteImport = createFileRoute('/_main/kassa/')()
const MainManagersManagersLazyRouteImport = createFileRoute(
  '/_main/_managers/managers',
)()
const MainTrucksTruckIndexLazyRouteImport = createFileRoute(
  '/_main/_trucks/truck/',
)()
const MainTripTripIndexLazyRouteImport = createFileRoute('/_main/_trip/trip/')()
const MainSettingsVehicleTypesIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/vehicle-types/',
)()
const MainSettingsUsersIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/users/',
)()
const MainSettingsRolesIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/roles/',
)()
const MainSettingsPaymentTypesIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/payment-types/',
)()
const MainSettingsLocationsIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/locations/',
)()
const MainSettingsExpenseTypesIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/expense-types/',
)()
const MainSettingsDriversIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/drivers/',
)()
const MainSettingsCustomersIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/customers/',
)()
const MainSettingsCargoTypesIndexLazyRouteImport = createFileRoute(
  '/_main/_settings/cargo-types/',
)()
const MainManagersTransportsIndexLazyRouteImport = createFileRoute(
  '/_main/_managers/transports/',
)()
const MainManagersTechnicCheckIndexLazyRouteImport = createFileRoute(
  '/_main/_managers/technic-check/',
)()

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardLazyRoute = MainDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/dashboard.lazy').then((d) => d.Route),
)
const AuthAuthLazyRoute = AuthAuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))
const MainTexnikCheckIndexLazyRoute =
  MainTexnikCheckIndexLazyRouteImport.update({
    id: '/texnik-check/',
    path: '/texnik-check/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/texnik-check/index.lazy').then((d) => d.Route),
  )
const MainMoliyaIndexLazyRoute = MainMoliyaIndexLazyRouteImport.update({
  id: '/moliya/',
  path: '/moliya/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/moliya/index.lazy').then((d) => d.Route),
)
const MainKassaIndexLazyRoute = MainKassaIndexLazyRouteImport.update({
  id: '/kassa/',
  path: '/kassa/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/kassa/index.lazy').then((d) => d.Route),
)
const MainManagersManagersLazyRoute =
  MainManagersManagersLazyRouteImport.update({
    id: '/_managers/managers',
    path: '/managers',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_managers/managers.lazy').then((d) => d.Route),
  )
const MainTrucksTruckIndexLazyRoute =
  MainTrucksTruckIndexLazyRouteImport.update({
    id: '/_trucks/truck/',
    path: '/truck/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_trucks/truck/index.lazy').then((d) => d.Route),
  )
const MainTripTripIndexLazyRoute = MainTripTripIndexLazyRouteImport.update({
  id: '/_trip/trip/',
  path: '/trip/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/_trip/trip/index.lazy').then((d) => d.Route),
)
const MainSettingsVehicleTypesIndexLazyRoute =
  MainSettingsVehicleTypesIndexLazyRouteImport.update({
    id: '/_settings/vehicle-types/',
    path: '/vehicle-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/vehicle-types/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainSettingsUsersIndexLazyRoute =
  MainSettingsUsersIndexLazyRouteImport.update({
    id: '/_settings/users/',
    path: '/users/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/users/index.lazy').then((d) => d.Route),
  )
const MainSettingsRolesIndexLazyRoute =
  MainSettingsRolesIndexLazyRouteImport.update({
    id: '/_settings/roles/',
    path: '/roles/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/roles/index.lazy').then((d) => d.Route),
  )
const MainSettingsPaymentTypesIndexLazyRoute =
  MainSettingsPaymentTypesIndexLazyRouteImport.update({
    id: '/_settings/payment-types/',
    path: '/payment-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/payment-types/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainSettingsLocationsIndexLazyRoute =
  MainSettingsLocationsIndexLazyRouteImport.update({
    id: '/_settings/locations/',
    path: '/locations/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/locations/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainSettingsExpenseTypesIndexLazyRoute =
  MainSettingsExpenseTypesIndexLazyRouteImport.update({
    id: '/_settings/expense-types/',
    path: '/expense-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/expense-types/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainSettingsDriversIndexLazyRoute =
  MainSettingsDriversIndexLazyRouteImport.update({
    id: '/_settings/drivers/',
    path: '/drivers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/drivers/index.lazy').then((d) => d.Route),
  )
const MainSettingsCustomersIndexLazyRoute =
  MainSettingsCustomersIndexLazyRouteImport.update({
    id: '/_settings/customers/',
    path: '/customers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/customers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainSettingsCargoTypesIndexLazyRoute =
  MainSettingsCargoTypesIndexLazyRouteImport.update({
    id: '/_settings/cargo-types/',
    path: '/cargo-types/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_settings/cargo-types/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainManagersTransportsIndexLazyRoute =
  MainManagersTransportsIndexLazyRouteImport.update({
    id: '/_managers/transports/',
    path: '/transports/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_managers/transports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainManagersTechnicCheckIndexLazyRoute =
  MainManagersTechnicCheckIndexLazyRouteImport.update({
    id: '/_managers/technic-check/',
    path: '/technic-check/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/_managers/technic-check/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainTrucksTruckDetailIdRoute = MainTrucksTruckDetailIdRouteImport.update({
  id: '/_trucks/truck-detail/$id',
  path: '/truck-detail/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainTrucksOrdersIdRoute = MainTrucksOrdersIdRouteImport.update({
  id: '/_trucks/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainManagersManagerTripsIdRoute =
  MainManagersManagerTripsIdRouteImport.update({
    id: '/_managers/manager-trips/$id',
    path: '/manager-trips/$id',
    getParentRoute: () => MainRoute,
  } as any)
const MainTripTripParentIdIndexRoute =
  MainTripTripParentIdIndexRouteImport.update({
    id: '/_trip/trip/$parentId/',
    path: '/trip/$parentId/',
    getParentRoute: () => MainRoute,
  } as any)
const MainTripTripParentIdChildIdRoute =
  MainTripTripParentIdChildIdRouteImport.update({
    id: '/_trip/trip/$parentId/$childId',
    path: '/trip/$parentId/$childId',
    getParentRoute: () => MainRoute,
  } as any)
const MainManagersManagerTripsManagerReysIdRoute =
  MainManagersManagerTripsManagerReysIdRouteImport.update({
    id: '/_managers/manager-trips/manager-reys/$id',
    path: '/manager-trips/manager-reys/$id',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/managers': typeof MainManagersManagersLazyRoute
  '/kassa/': typeof MainKassaIndexLazyRoute
  '/moliya/': typeof MainMoliyaIndexLazyRoute
  '/texnik-check/': typeof MainTexnikCheckIndexLazyRoute
  '/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/orders/$id': typeof MainTrucksOrdersIdRoute
  '/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/technic-check/': typeof MainManagersTechnicCheckIndexLazyRoute
  '/transports/': typeof MainManagersTransportsIndexLazyRoute
  '/cargo-types/': typeof MainSettingsCargoTypesIndexLazyRoute
  '/customers/': typeof MainSettingsCustomersIndexLazyRoute
  '/drivers/': typeof MainSettingsDriversIndexLazyRoute
  '/expense-types/': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/locations/': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types/': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles/': typeof MainSettingsRolesIndexLazyRoute
  '/users/': typeof MainSettingsUsersIndexLazyRoute
  '/vehicle-types/': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/trip/': typeof MainTripTripIndexLazyRoute
  '/truck/': typeof MainTrucksTruckIndexLazyRoute
  '/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/trip/$parentId/': typeof MainTripTripParentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthAuthLazyRoute
  '/dashboard': typeof MainDashboardLazyRoute
  '/managers': typeof MainManagersManagersLazyRoute
  '/kassa': typeof MainKassaIndexLazyRoute
  '/moliya': typeof MainMoliyaIndexLazyRoute
  '/texnik-check': typeof MainTexnikCheckIndexLazyRoute
  '/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/orders/$id': typeof MainTrucksOrdersIdRoute
  '/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/technic-check': typeof MainManagersTechnicCheckIndexLazyRoute
  '/transports': typeof MainManagersTransportsIndexLazyRoute
  '/cargo-types': typeof MainSettingsCargoTypesIndexLazyRoute
  '/customers': typeof MainSettingsCustomersIndexLazyRoute
  '/drivers': typeof MainSettingsDriversIndexLazyRoute
  '/expense-types': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/locations': typeof MainSettingsLocationsIndexLazyRoute
  '/payment-types': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/roles': typeof MainSettingsRolesIndexLazyRoute
  '/users': typeof MainSettingsUsersIndexLazyRoute
  '/vehicle-types': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/trip': typeof MainTripTripIndexLazyRoute
  '/truck': typeof MainTrucksTruckIndexLazyRoute
  '/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/trip/$parentId': typeof MainTripTripParentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/dashboard': typeof MainDashboardLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/_managers/managers': typeof MainManagersManagersLazyRoute
  '/_main/kassa/': typeof MainKassaIndexLazyRoute
  '/_main/moliya/': typeof MainMoliyaIndexLazyRoute
  '/_main/texnik-check/': typeof MainTexnikCheckIndexLazyRoute
  '/_main/_managers/manager-trips/$id': typeof MainManagersManagerTripsIdRoute
  '/_main/_trucks/orders/$id': typeof MainTrucksOrdersIdRoute
  '/_main/_trucks/truck-detail/$id': typeof MainTrucksTruckDetailIdRoute
  '/_main/_managers/technic-check/': typeof MainManagersTechnicCheckIndexLazyRoute
  '/_main/_managers/transports/': typeof MainManagersTransportsIndexLazyRoute
  '/_main/_settings/cargo-types/': typeof MainSettingsCargoTypesIndexLazyRoute
  '/_main/_settings/customers/': typeof MainSettingsCustomersIndexLazyRoute
  '/_main/_settings/drivers/': typeof MainSettingsDriversIndexLazyRoute
  '/_main/_settings/expense-types/': typeof MainSettingsExpenseTypesIndexLazyRoute
  '/_main/_settings/locations/': typeof MainSettingsLocationsIndexLazyRoute
  '/_main/_settings/payment-types/': typeof MainSettingsPaymentTypesIndexLazyRoute
  '/_main/_settings/roles/': typeof MainSettingsRolesIndexLazyRoute
  '/_main/_settings/users/': typeof MainSettingsUsersIndexLazyRoute
  '/_main/_settings/vehicle-types/': typeof MainSettingsVehicleTypesIndexLazyRoute
  '/_main/_trip/trip/': typeof MainTripTripIndexLazyRoute
  '/_main/_trucks/truck/': typeof MainTrucksTruckIndexLazyRoute
  '/_main/_managers/manager-trips/manager-reys/$id': typeof MainManagersManagerTripsManagerReysIdRoute
  '/_main/_trip/trip/$parentId/$childId': typeof MainTripTripParentIdChildIdRoute
  '/_main/_trip/trip/$parentId/': typeof MainTripTripParentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/managers'
    | '/kassa/'
    | '/moliya/'
    | '/texnik-check/'
    | '/manager-trips/$id'
    | '/orders/$id'
    | '/truck-detail/$id'
    | '/technic-check/'
    | '/transports/'
    | '/cargo-types/'
    | '/customers/'
    | '/drivers/'
    | '/expense-types/'
    | '/locations/'
    | '/payment-types/'
    | '/roles/'
    | '/users/'
    | '/vehicle-types/'
    | '/trip/'
    | '/truck/'
    | '/manager-trips/manager-reys/$id'
    | '/trip/$parentId/$childId'
    | '/trip/$parentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/managers'
    | '/kassa'
    | '/moliya'
    | '/texnik-check'
    | '/manager-trips/$id'
    | '/orders/$id'
    | '/truck-detail/$id'
    | '/technic-check'
    | '/transports'
    | '/cargo-types'
    | '/customers'
    | '/drivers'
    | '/expense-types'
    | '/locations'
    | '/payment-types'
    | '/roles'
    | '/users'
    | '/vehicle-types'
    | '/trip'
    | '/truck'
    | '/manager-trips/manager-reys/$id'
    | '/trip/$parentId/$childId'
    | '/trip/$parentId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/dashboard'
    | '/_main/'
    | '/_main/_managers/managers'
    | '/_main/kassa/'
    | '/_main/moliya/'
    | '/_main/texnik-check/'
    | '/_main/_managers/manager-trips/$id'
    | '/_main/_trucks/orders/$id'
    | '/_main/_trucks/truck-detail/$id'
    | '/_main/_managers/technic-check/'
    | '/_main/_managers/transports/'
    | '/_main/_settings/cargo-types/'
    | '/_main/_settings/customers/'
    | '/_main/_settings/drivers/'
    | '/_main/_settings/expense-types/'
    | '/_main/_settings/locations/'
    | '/_main/_settings/payment-types/'
    | '/_main/_settings/roles/'
    | '/_main/_settings/users/'
    | '/_main/_settings/vehicle-types/'
    | '/_main/_trip/trip/'
    | '/_main/_trucks/truck/'
    | '/_main/_managers/manager-trips/manager-reys/$id'
    | '/_main/_trip/trip/$parentId/$childId'
    | '/_main/_trip/trip/$parentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/texnik-check/': {
      id: '/_main/texnik-check/'
      path: '/texnik-check'
      fullPath: '/texnik-check/'
      preLoaderRoute: typeof MainTexnikCheckIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/moliya/': {
      id: '/_main/moliya/'
      path: '/moliya'
      fullPath: '/moliya/'
      preLoaderRoute: typeof MainMoliyaIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/kassa/': {
      id: '/_main/kassa/'
      path: '/kassa'
      fullPath: '/kassa/'
      preLoaderRoute: typeof MainKassaIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_managers/managers': {
      id: '/_main/_managers/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof MainManagersManagersLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trucks/truck/': {
      id: '/_main/_trucks/truck/'
      path: '/truck'
      fullPath: '/truck/'
      preLoaderRoute: typeof MainTrucksTruckIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trip/trip/': {
      id: '/_main/_trip/trip/'
      path: '/trip'
      fullPath: '/trip/'
      preLoaderRoute: typeof MainTripTripIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/vehicle-types/': {
      id: '/_main/_settings/vehicle-types/'
      path: '/vehicle-types'
      fullPath: '/vehicle-types/'
      preLoaderRoute: typeof MainSettingsVehicleTypesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/users/': {
      id: '/_main/_settings/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof MainSettingsUsersIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/roles/': {
      id: '/_main/_settings/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof MainSettingsRolesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/payment-types/': {
      id: '/_main/_settings/payment-types/'
      path: '/payment-types'
      fullPath: '/payment-types/'
      preLoaderRoute: typeof MainSettingsPaymentTypesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/locations/': {
      id: '/_main/_settings/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof MainSettingsLocationsIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/expense-types/': {
      id: '/_main/_settings/expense-types/'
      path: '/expense-types'
      fullPath: '/expense-types/'
      preLoaderRoute: typeof MainSettingsExpenseTypesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/drivers/': {
      id: '/_main/_settings/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof MainSettingsDriversIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/customers/': {
      id: '/_main/_settings/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof MainSettingsCustomersIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_settings/cargo-types/': {
      id: '/_main/_settings/cargo-types/'
      path: '/cargo-types'
      fullPath: '/cargo-types/'
      preLoaderRoute: typeof MainSettingsCargoTypesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_managers/transports/': {
      id: '/_main/_managers/transports/'
      path: '/transports'
      fullPath: '/transports/'
      preLoaderRoute: typeof MainManagersTransportsIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_managers/technic-check/': {
      id: '/_main/_managers/technic-check/'
      path: '/technic-check'
      fullPath: '/technic-check/'
      preLoaderRoute: typeof MainManagersTechnicCheckIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trucks/truck-detail/$id': {
      id: '/_main/_trucks/truck-detail/$id'
      path: '/truck-detail/$id'
      fullPath: '/truck-detail/$id'
      preLoaderRoute: typeof MainTrucksTruckDetailIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trucks/orders/$id': {
      id: '/_main/_trucks/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof MainTrucksOrdersIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_managers/manager-trips/$id': {
      id: '/_main/_managers/manager-trips/$id'
      path: '/manager-trips/$id'
      fullPath: '/manager-trips/$id'
      preLoaderRoute: typeof MainManagersManagerTripsIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trip/trip/$parentId/': {
      id: '/_main/_trip/trip/$parentId/'
      path: '/trip/$parentId'
      fullPath: '/trip/$parentId/'
      preLoaderRoute: typeof MainTripTripParentIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_trip/trip/$parentId/$childId': {
      id: '/_main/_trip/trip/$parentId/$childId'
      path: '/trip/$parentId/$childId'
      fullPath: '/trip/$parentId/$childId'
      preLoaderRoute: typeof MainTripTripParentIdChildIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_managers/manager-trips/manager-reys/$id': {
      id: '/_main/_managers/manager-trips/manager-reys/$id'
      path: '/manager-trips/manager-reys/$id'
      fullPath: '/manager-trips/manager-reys/$id'
      preLoaderRoute: typeof MainManagersManagerTripsManagerReysIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainDashboardLazyRoute: typeof MainDashboardLazyRoute
  MainIndexRoute: typeof MainIndexRoute
  MainManagersManagersLazyRoute: typeof MainManagersManagersLazyRoute
  MainKassaIndexLazyRoute: typeof MainKassaIndexLazyRoute
  MainMoliyaIndexLazyRoute: typeof MainMoliyaIndexLazyRoute
  MainTexnikCheckIndexLazyRoute: typeof MainTexnikCheckIndexLazyRoute
  MainManagersManagerTripsIdRoute: typeof MainManagersManagerTripsIdRoute
  MainTrucksOrdersIdRoute: typeof MainTrucksOrdersIdRoute
  MainTrucksTruckDetailIdRoute: typeof MainTrucksTruckDetailIdRoute
  MainManagersTechnicCheckIndexLazyRoute: typeof MainManagersTechnicCheckIndexLazyRoute
  MainManagersTransportsIndexLazyRoute: typeof MainManagersTransportsIndexLazyRoute
  MainSettingsCargoTypesIndexLazyRoute: typeof MainSettingsCargoTypesIndexLazyRoute
  MainSettingsCustomersIndexLazyRoute: typeof MainSettingsCustomersIndexLazyRoute
  MainSettingsDriversIndexLazyRoute: typeof MainSettingsDriversIndexLazyRoute
  MainSettingsExpenseTypesIndexLazyRoute: typeof MainSettingsExpenseTypesIndexLazyRoute
  MainSettingsLocationsIndexLazyRoute: typeof MainSettingsLocationsIndexLazyRoute
  MainSettingsPaymentTypesIndexLazyRoute: typeof MainSettingsPaymentTypesIndexLazyRoute
  MainSettingsRolesIndexLazyRoute: typeof MainSettingsRolesIndexLazyRoute
  MainSettingsUsersIndexLazyRoute: typeof MainSettingsUsersIndexLazyRoute
  MainSettingsVehicleTypesIndexLazyRoute: typeof MainSettingsVehicleTypesIndexLazyRoute
  MainTripTripIndexLazyRoute: typeof MainTripTripIndexLazyRoute
  MainTrucksTruckIndexLazyRoute: typeof MainTrucksTruckIndexLazyRoute
  MainManagersManagerTripsManagerReysIdRoute: typeof MainManagersManagerTripsManagerReysIdRoute
  MainTripTripParentIdChildIdRoute: typeof MainTripTripParentIdChildIdRoute
  MainTripTripParentIdIndexRoute: typeof MainTripTripParentIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardLazyRoute: MainDashboardLazyRoute,
  MainIndexRoute: MainIndexRoute,
  MainManagersManagersLazyRoute: MainManagersManagersLazyRoute,
  MainKassaIndexLazyRoute: MainKassaIndexLazyRoute,
  MainMoliyaIndexLazyRoute: MainMoliyaIndexLazyRoute,
  MainTexnikCheckIndexLazyRoute: MainTexnikCheckIndexLazyRoute,
  MainManagersManagerTripsIdRoute: MainManagersManagerTripsIdRoute,
  MainTrucksOrdersIdRoute: MainTrucksOrdersIdRoute,
  MainTrucksTruckDetailIdRoute: MainTrucksTruckDetailIdRoute,
  MainManagersTechnicCheckIndexLazyRoute:
    MainManagersTechnicCheckIndexLazyRoute,
  MainManagersTransportsIndexLazyRoute: MainManagersTransportsIndexLazyRoute,
  MainSettingsCargoTypesIndexLazyRoute: MainSettingsCargoTypesIndexLazyRoute,
  MainSettingsCustomersIndexLazyRoute: MainSettingsCustomersIndexLazyRoute,
  MainSettingsDriversIndexLazyRoute: MainSettingsDriversIndexLazyRoute,
  MainSettingsExpenseTypesIndexLazyRoute:
    MainSettingsExpenseTypesIndexLazyRoute,
  MainSettingsLocationsIndexLazyRoute: MainSettingsLocationsIndexLazyRoute,
  MainSettingsPaymentTypesIndexLazyRoute:
    MainSettingsPaymentTypesIndexLazyRoute,
  MainSettingsRolesIndexLazyRoute: MainSettingsRolesIndexLazyRoute,
  MainSettingsUsersIndexLazyRoute: MainSettingsUsersIndexLazyRoute,
  MainSettingsVehicleTypesIndexLazyRoute:
    MainSettingsVehicleTypesIndexLazyRoute,
  MainTripTripIndexLazyRoute: MainTripTripIndexLazyRoute,
  MainTrucksTruckIndexLazyRoute: MainTrucksTruckIndexLazyRoute,
  MainManagersManagerTripsManagerReysIdRoute:
    MainManagersManagerTripsManagerReysIdRoute,
  MainTripTripParentIdChildIdRoute: MainTripTripParentIdChildIdRoute,
  MainTripTripParentIdIndexRoute: MainTripTripParentIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
